- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  become_user: ubuntu
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: sudo docker run -itd -p 8082:8082 yatish03/banking-project:1.0
